add_subdirectory(StopWatch)
add_subdirectory(MatrixSolver)
add_subdirectory(FunctionIntegrator)
add_subdirectory(ReadReaclib)
add_subdirectory(ReadFFN)
add_subdirectory(ReadWebnucleo)
add_subdirectory(ReadWinv)
add_subdirectory(ReadFissionReactions)
add_subdirectory(NetworkOutput)
add_subdirectory(NSE)
add_subdirectory(NSE_screening)
add_subdirectory(HelmholtzEOS)
add_subdirectory(TrivialNetworks)
add_subdirectory(SmallNetworks)
add_subdirectory(AlphaNetwork)
add_subdirectory(NeutrinoNetwork)
add_subdirectory(FortranOperatorSplitting)
add_subdirectory(InverseRates)
add_subdirectory(XRayBurst)
if (NOT ${SKYNET_USE_DENSE_SOLVER})
  add_subdirectory(ReactionTurnOff)
  add_subdirectory(r-process)
  add_subdirectory(NSEEvolution)
endif()
