add_subdirectory(r-process)
if(USE_MOVIE)
  add_subdirectory(movie)
endif()

FILE(GLOB python_scripts "${CMAKE_CURRENT_SOURCE_DIR}/*.py")

install(FILES ${python_scripts}
  DESTINATION "${INSTALL_EXAMPLES_DIR}"
  PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE
)

install(DIRECTORY parallel/
  DESTINATION "${INSTALL_EXAMPLES_DIR}/parallel"
  USE_SOURCE_PERMISSIONS
)

install(DIRECTORY code_tests/
  DESTINATION "${INSTALL_EXAMPLES_DIR}/code_tests"
  USE_SOURCE_PERMISSIONS
)
